SOURCE_RUNTIME_API_KEY = "TRACECAT_SOURCE_API_KEY"
SOURCE_RUNTIME_API_KEY_HEADER = "TRACECAT_SOURCE_API_KEY_HEADER"
SOURCE_RUNTIME_API_VERSION = "TRACECAT_SOURCE_API_VERSION"
SOURCE_RUNTIME_BASE_URL = "TRACECAT_SOURCE_BASE_URL"
