type: action
definition:
  title: Get label names
  description: Retrieve a list of label names from Prometheus metrics, optionally filtered by series selectors.
  display_group: Prometheus
  doc_url: https://prometheus.io/docs/prometheus/latest/querying/api/#getting-label-names
  namespace: tools.prometheus
  name: get_label_names
  secrets:
    - name: prometheus
      keys: ["PROMETHEUS_API_TOKEN"]
      optional: true
  expects:
    match:
      type: list[str]
      description: Series selector to filter the returned label names (e.g., ["up", "http_requests_total{job=\"api\"}"]). Can be repeated.
      default: []
    base_url:
      type: str
      description: Prometheus server URL (e.g., http://localhost:9090).
      default: "http://localhost:9090"
  steps:
    - ref: prometheus_label_names
      action: core.http_request
      args:
        url: ${{ inputs.base_url }}/api/v1/labels
        method: GET
        params:
          match[]: ${{ inputs.match }}
    - ref: human_readable
      action: core.transform.reshape
      args:
        value:
          status: "success"
          message: "Retrieved Prometheus label names"
          labels: ${{ steps.prometheus_label_names.result.data.data }}
          filter_applied: ${{ inputs.match }}
  returns: ${{ steps.human_readable.result }}
