apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.executor.service.name }}"
  namespace: {{ .Release.Namespace }}
{{- if .Values.executor.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.executor.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
  labels:
    app: tracecat
    chart: "{{ template "chart.fullname" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/component: executor
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/version: {{ template "chart.version" . }}
{{- if .Values.executor.service.labels }}
    {{- range $key, $value := .Values.executor.service.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  selector:
    app: tracecat
    app.kubernetes.io/component: executor
  type: ClusterIP
  ports:
    - name: tracecat-executor
      port: {{ .Values.executor.service.port }}
      protocol: TCP
      targetPort: {{ .Values.executor.service.port }}
