version: 2
updates:
  - package-ecosystem: "uv"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "tracecat*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
