FROM ghcr.io/astral-sh/uv:0.4.20-python3.12-bookworm-slim

# Define the environment variables
ENV UV_SYSTEM_PYTHON=1
ENV HOST=0.0.0.0
ENV PORT=8000

# Expose the application port
EXPOSE $PORT

# Install xmlsec1
RUN apt-get update && apt-get install -y xmlsec1

# Set the working directory inside the container
WORKDIR /app

# Copy the application files into the container
COPY ./tracecat /app/tracecat
COPY ./registry /app/registry
COPY ./pyproject.toml /app/pyproject.toml
COPY ./README.md /app/README.md
COPY ./LICENSE /app/LICENSE
COPY ./alembic.ini /app/alembic.ini
COPY ./alembic /app/alembic

COPY scripts/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Install package and registry in editable mode
RUN uv pip install -e .
RUN uv pip install -e ./registry

# Create symlink for uv binary to point to /root/.local/bin/uv
RUN mkdir -p ~/.local/bin && ln -s $(command -v uv) ~/.local/bin/uv

# Install git
RUN apt-get update && apt-get install -y git

ENTRYPOINT ["/app/entrypoint.sh"]

# Command to run the application
CMD ["sh", "-c", "python3 -m uvicorn tracecat.api.app:app --host $HOST --port $PORT --reload"]
