# Non-development docker compose extension file
# - Removes all volume bindings
# -
services:
  api:
    volumes: []
    environment:
      TRACECAT__APP_ENV: production

  worker:
    volumes: []
    environment:
      TRACECAT__APP_ENV: production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes: []
    environment:
      NEXT_PUBLIC_APP_ENV: production

  postgres_db:
    volumes: []

volumes: null
