# Non-development docker compose extension file
# - Removes all volume bindings
# - Uses the multi-stage frontend Dockerfile
# - Changes env vars to production
services:
  api:
    volumes: []
    environment:
      TRACECAT__APP_ENV: production
      # NOTE: Postgres SSL mode is disabled in local deployments
      TRACECAT__DB_SSLMODE: disable

  worker:
    volumes: []
    environment:
      TRACECAT__APP_ENV: production
      # NOTE: Postgres SSL mode is disabled in local deployments
      TRACECAT__DB_SSLMODE: disable

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes: []
    environment:
      NEXT_PUBLIC_APP_ENV: production

  postgres_db:
    volumes: []

volumes: null
