{{- if .Values.executor.serviceAccount.create }}
{{- $annotations := mergeOverwrite (dict) .Values.serviceAccount.annotations .Values.executor.serviceAccount.annotations }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tracecat.executorServiceAccountName" . }}
  labels:
    {{- include "tracecat.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
