type: action
definition:
  title: Create Kubernetes Job
  description: Create a job in a Kubernetes cluster.
  namespace: tools.kubernetes
  name: create_job
  expects:
    name:
      type: str
      description: Name of the job to create.
    image:
      type: str
      description: Container image to use for the job.
    command:
      type: str
      description: Command to execute in the job.
    namespace:
      type: str
      description: Namespace to create the job in.
  steps:
    - ref: create_job
      action: ee.kubectl.run_command
      args:
        command:
          - create
          - job
          - ${{ inputs.name }}
          - --image=${{ inputs.image }}
          - -n
          - ${{ inputs.namespace }}
          - --
          - /bin/sh
          - -c
          - ${{ inputs.command }}
        namespace: ${{ inputs.namespace }}
  returns: ${{ steps.create_job.result }}
