type: action
definition:
  title: Get logs
  description: Print logs from a pod.
  display_group: Kubernetes
  doc_url: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#logs
  namespace: ee.kubernetes
  name: logs
  expects:
    pod:
      type: str
      description: Name of the pod to get logs from.
    namespace:
      type: str
      description: Namespace of the pod.
  steps:
    - ref: get_logs
      action: ee.kubernetes.run_command
      args:
        command:
          - kubectl
          - logs
          - ${{ inputs.pod }}
        namespace: ${{ inputs.namespace }}
  returns: ${{ steps.get_logs.result }}
