definition:
  title: Receive Panther alert
  description: |
    Receive a Panther alert, convert `createdAt` string to datetime, and deserialize `alertContext` JSON object.
  entrypoint:
    ref: deserialize_alert
    expects:
      id:
        type: str
        description: Unique identifier for the alert
      createdAt:
        type: str
        description: Timestamp when the alert was created
      severity:
        type: str
        description: Severity level of the alert
      type:
        type: str
        description: Type of the alert
      link:
        type: str
        description: Link to the alert details
      title:
        type: str
        description: Title of the alert
      name:
        type: str
        description: Name associated with the alert
      alertId:
        type: str
        description: Alert identifier
      description:
        type: str
        description: Description of the alert
      runbook:
        type: str
        description: Runbook associated with the alert
      tags:
        type: list[str]
        description: Tags associated with the alert
      version:
        type: str
        description: Version of the alert
      alertContext:
        type: str
        description: Serialized JSON object containing additional context for the alert
  triggers:
    - type: webhook
      ref: receive_panther_alert
      entrypoint: deserialize_alert

  actions:
    - ref: deserialize_alert
      action: core.transform.reshape
      args:
        value:
          id: ${{ TRIGGER.id}}
          createdAt: ${{ FN.to_datetime(TRIGGER.createdAt)}}
          severity: ${{ TRIGGER.severity}}
          type: ${{ TRIGGER.type}}
          link: ${{ TRIGGER.link}}
          title: ${{ TRIGGER.title}}
          name: ${{ TRIGGER.name}}
          alertId: ${{ TRIGGER.alertId}}
          description: ${{ TRIGGER.description}}
          runbook: ${{ TRIGGER.runbook}}
          tags: ${{ TRIGGER.tags}}
          version: ${{ TRIGGER.version}}
          alertContext: ${{ FN.deserialize_json(TRIGGER.alertContext)}}
