# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
# pyright: reportAttributeAccessIssue=false

import grpc

from tracecat.auth.dex import api_pb2 as tracecat_dot_auth_dot_dex_dot_api__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in tracecat/auth/dex/api_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DexStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePassword = channel.unary_unary(
            "/api.Dex/CreatePassword",
            request_serializer=tracecat_dot_auth_dot_dex_dot_api__pb2.CreatePasswordReq.SerializeToString,
            response_deserializer=tracecat_dot_auth_dot_dex_dot_api__pb2.CreatePasswordResp.FromString,
            _registered_method=True,
        )
        self.UpdatePassword = channel.unary_unary(
            "/api.Dex/UpdatePassword",
            request_serializer=tracecat_dot_auth_dot_dex_dot_api__pb2.UpdatePasswordReq.SerializeToString,
            response_deserializer=tracecat_dot_auth_dot_dex_dot_api__pb2.UpdatePasswordResp.FromString,
            _registered_method=True,
        )
        self.DeletePassword = channel.unary_unary(
            "/api.Dex/DeletePassword",
            request_serializer=tracecat_dot_auth_dot_dex_dot_api__pb2.DeletePasswordReq.SerializeToString,
            response_deserializer=tracecat_dot_auth_dot_dex_dot_api__pb2.DeletePasswordResp.FromString,
            _registered_method=True,
        )
        self.ListConnectors = channel.unary_unary(
            "/api.Dex/ListConnectors",
            request_serializer=tracecat_dot_auth_dot_dex_dot_api__pb2.ListConnectorReq.SerializeToString,
            response_deserializer=tracecat_dot_auth_dot_dex_dot_api__pb2.ListConnectorResp.FromString,
            _registered_method=True,
        )


class DexServicer:
    """Missing associated documentation comment in .proto file."""

    def CreatePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdatePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeletePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListConnectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DexServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreatePassword": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePassword,
            request_deserializer=tracecat_dot_auth_dot_dex_dot_api__pb2.CreatePasswordReq.FromString,
            response_serializer=tracecat_dot_auth_dot_dex_dot_api__pb2.CreatePasswordResp.SerializeToString,
        ),
        "UpdatePassword": grpc.unary_unary_rpc_method_handler(
            servicer.UpdatePassword,
            request_deserializer=tracecat_dot_auth_dot_dex_dot_api__pb2.UpdatePasswordReq.FromString,
            response_serializer=tracecat_dot_auth_dot_dex_dot_api__pb2.UpdatePasswordResp.SerializeToString,
        ),
        "DeletePassword": grpc.unary_unary_rpc_method_handler(
            servicer.DeletePassword,
            request_deserializer=tracecat_dot_auth_dot_dex_dot_api__pb2.DeletePasswordReq.FromString,
            response_serializer=tracecat_dot_auth_dot_dex_dot_api__pb2.DeletePasswordResp.SerializeToString,
        ),
        "ListConnectors": grpc.unary_unary_rpc_method_handler(
            servicer.ListConnectors,
            request_deserializer=tracecat_dot_auth_dot_dex_dot_api__pb2.ListConnectorReq.FromString,
            response_serializer=tracecat_dot_auth_dot_dex_dot_api__pb2.ListConnectorResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "api.Dex", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("api.Dex", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Dex:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePassword(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.Dex/CreatePassword",
            tracecat_dot_auth_dot_dex_dot_api__pb2.CreatePasswordReq.SerializeToString,
            tracecat_dot_auth_dot_dex_dot_api__pb2.CreatePasswordResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdatePassword(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.Dex/UpdatePassword",
            tracecat_dot_auth_dot_dex_dot_api__pb2.UpdatePasswordReq.SerializeToString,
            tracecat_dot_auth_dot_dex_dot_api__pb2.UpdatePasswordResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeletePassword(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.Dex/DeletePassword",
            tracecat_dot_auth_dot_dex_dot_api__pb2.DeletePasswordReq.SerializeToString,
            tracecat_dot_auth_dot_dex_dot_api__pb2.DeletePasswordResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListConnectors(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/api.Dex/ListConnectors",
            tracecat_dot_auth_dot_dex_dot_api__pb2.ListConnectorReq.SerializeToString,
            tracecat_dot_auth_dot_dex_dot_api__pb2.ListConnectorResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
