apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.api.service.name }}"
  namespace: {{ .Release.Namespace }}
{{- if .Values.api.service.annotations }}
  annotations:
    {{- range $key, $value := .Values.api.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
  labels:
    app: tracecat
    chart: "{{ template "chart.fullname" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/component: api
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/version: {{ template "chart.version" . }}
{{- if .Values.api.service.labels }}
    {{- range $key, $value := .Values.api.service.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  selector:
    app: tracecat
    app.kubernetes.io/component: api
  type: ClusterIP
  ports:
    - name: tracecat-api
      port: {{ .Values.api.service.port }}
      protocol: TCP
      targetPort: 8000
