"""make workspace_id non-nullable for workspace-scoped models

Revision ID: 0fd1f09cd98b
Revises: a1b2c3d4e5f6
Create Date: 2025-12-04 14:14:05.910579

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fd1f09cd98b"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent_preset", "workspace_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "case_duration", "workspace_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "case_duration_definition",
        "workspace_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column("case_tag", "workspace_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("secret", "workspace_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("tag", "workspace_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("workflow", "workspace_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "workflow_folder", "workspace_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_folder", "workspace_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column("workflow", "workspace_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("tag", "workspace_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("secret", "workspace_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("case_tag", "workspace_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "case_duration_definition",
        "workspace_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "case_duration", "workspace_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "agent_preset", "workspace_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
