"""add_parent_session_id_for_session_forking

Revision ID: 145c4c163ace
Revises: 7aab03def5b6
Create Date: 2026-01-16 19:33:19.446416

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "145c4c163ace"
down_revision: str | None = "7aab03def5b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_session", sa.Column("parent_session_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        op.f("ix_agent_session_parent_session_id"),
        "agent_session",
        ["parent_session_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_agent_session_parent_session_id_agent_session"),
        "agent_session",
        "agent_session",
        ["parent_session_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_agent_session_parent_session_id_agent_session"),
        "agent_session",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_agent_session_parent_session_id"), table_name="agent_session"
    )
    op.drop_column("agent_session", "parent_session_id")
    # ### end Alembic commands ###
