"""jsonb schema validation case fields

Revision ID: 3f1bacf5a8a9
Revises: c13c1c2f4d93
Create Date: 2025-11-25 20:33:14.153722

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f1bacf5a8a9"
down_revision: str | None = "c13c1c2f4d93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case_fields",
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.drop_constraint("case_fields_case_id_key", "case_fields", type_="unique")
    op.create_unique_constraint("uq_case_fields_owner", "case_fields", ["owner_id"])
    op.drop_constraint("case_fields_case_id_fkey", "case_fields", type_="foreignkey")
    op.drop_column("case_fields", "case_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case_fields",
        sa.Column("case_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "case_fields_case_id_fkey",
        "case_fields",
        "cases",
        ["case_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_case_fields_owner", "case_fields", type_="unique")
    op.create_unique_constraint(
        "case_fields_case_id_key",
        "case_fields",
        ["case_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("case_fields", "schema")
    # ### end Alembic commands ###
