"""Add expects to Workflow

Revision ID: 5308ffdd79f3
Revises: c4620fec7efc
Create Date: 2024-09-15 00:46:01.462718

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5308ffdd79f3"
down_revision: str | None = "c4620fec7efc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow",
        sa.Column("expects", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow", "expects")
    # ### end Alembic commands ###
