"""default trigger values for case tasks

Revision ID: 7b9dbaecb03a
Revises: 51dc33f1322a
Create Date: 2025-11-30 19:05:06.209022

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b9dbaecb03a"
down_revision: str | None = "51dc33f1322a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case_task",
        sa.Column(
            "default_trigger_values",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case_task", "default_trigger_values")
    # ### end Alembic commands ###
