"""add_model_settings_to_agent_preset

Revision ID: 875ce39a9abb
Revises: 2ef382e77dea
Create Date: 2025-11-21 16:45:01.263049

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "875ce39a9abb"
down_revision: str | None = "2ef382e77dea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_preset",
        sa.Column(
            "model_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###

    # Set enable_thinking to true for all existing presets without structured outputs
    # This maintains the current behavior where thinking was always enabled
    connection = op.get_bind()
    _ = connection.execute(
        sa.text("""
            UPDATE agent_preset
            SET model_settings = '{"enable_thinking": true}'::jsonb
            WHERE model_settings IS NULL
              AND (output_type IS NULL OR output_type::text !~ '"type"\\s*:');
        """)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_preset", "model_settings")
    # ### end Alembic commands ###
