"""add case attachments

Revision ID: 9a001807d27b
Revises: 71c8649f752f
Create Date: 2025-07-02 11:30:09.686449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '9a001807d27b'
down_revision: Union[str, None] = '71c8649f752f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('surrogate_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('surrogate_id')
    )
    op.create_index(op.f('ix_file_id'), 'file', ['id'], unique=True)
    op.create_index(op.f('ix_file_sha256'), 'file', ['sha256'], unique=False)
    op.create_table('case_attachment',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'file_id', name='uq_case_attachment_case_file')
    )
    op.create_index(op.f('ix_case_attachment_id'), 'case_attachment', ['id'], unique=True)
    op.sync_enum_values('public', 'caseeventtype', ['CASE_CREATED', 'CASE_UPDATED', 'CASE_CLOSED', 'CASE_REOPENED', 'PRIORITY_CHANGED', 'SEVERITY_CHANGED', 'STATUS_CHANGED', 'FIELDS_CHANGED', 'ASSIGNEE_CHANGED', 'ATTACHMENT_CREATED', 'ATTACHMENT_DELETED'],
                        [TableReference(table_schema='public', table_name='case_event', column_name='type')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'caseeventtype', ['CASE_CREATED', 'CASE_UPDATED', 'CASE_CLOSED', 'CASE_REOPENED', 'PRIORITY_CHANGED', 'SEVERITY_CHANGED', 'STATUS_CHANGED', 'FIELDS_CHANGED', 'ASSIGNEE_CHANGED'],
                        [TableReference(table_schema='public', table_name='case_event', column_name='type')],
                        enum_values_to_rename=[])
    op.drop_index(op.f('ix_case_attachment_id'), table_name='case_attachment')
    op.drop_table('case_attachment')
    op.drop_index(op.f('ix_file_sha256'), table_name='file')
    op.drop_index(op.f('ix_file_id'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
