"""add_mcp_command_server_fields

Revision ID: cde97a0df056
Revises: 5a3b7c8d9e0f
Create Date: 2026-01-23 16:29:45.546977

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cde97a0df056"
down_revision: str | None = "5a3b7c8d9e0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_integration",
        sa.Column(
            "server_type", sa.String(length=20), server_default="url", nullable=False
        ),
    )
    op.add_column(
        "mcp_integration", sa.Column("command", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "mcp_integration",
        sa.Column(
            "command_args", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "mcp_integration",
        sa.Column(
            "command_env", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("mcp_integration", sa.Column("timeout", sa.Integer(), nullable=True))
    op.alter_column(
        "mcp_integration", "server_uri", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete command-type integrations first (they have NULL server_uri)
    op.execute("DELETE FROM mcp_integration WHERE server_type = 'command'")
    op.alter_column(
        "mcp_integration", "server_uri", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("mcp_integration", "timeout")
    op.drop_column("mcp_integration", "command_env")
    op.drop_column("mcp_integration", "command_args")
    op.drop_column("mcp_integration", "command")
    op.drop_column("mcp_integration", "server_type")
    # ### end Alembic commands ###
