"""forking agent sessions

Revision ID: d24dcec8a49c
Revises: f856d9b7ee5a
Create Date: 2026-01-15 22:07:49.909252

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d24dcec8a49c"
down_revision: str | None = "f856d9b7ee5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_session", sa.Column("parent_session_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        op.f("ix_agent_session_parent_session_id"),
        "agent_session",
        ["parent_session_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_agent_session_parent_session_id_agent_session"),
        "agent_session",
        "agent_session",
        ["parent_session_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_agent_session_parent_session_id_agent_session"),
        "agent_session",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_agent_session_parent_session_id"), table_name="agent_session"
    )
    op.drop_column("agent_session", "parent_session_id")
    # ### end Alembic commands ###
