"""audit logs

Revision ID: eadbdbb55cda
Revises: a1b2c3d4e5f6
Create Date: 2025-12-04 17:07:35.178333

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eadbdbb55cda"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("USER", name="auditeventactor").create(op.get_bind())
    sa.Enum("ATTEMPT", "SUCCESS", "FAILURE", name="auditeventstatus").create(
        op.get_bind()
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column(
            "actor_type",
            postgresql.ENUM("USER", name="auditeventactor", create_type=False),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("actor_display", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=128), nullable=True),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ATTEMPT",
                "SUCCESS",
                "FAILURE",
                name="auditeventstatus",
                create_type=False,
            ),
            nullable=False,
            server_default=sa.text("'SUCCESS'"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
        sa.UniqueConstraint("id", name=op.f("uq_audit_event_id")),
    )
    op.create_index(
        "ix_audit_event_actor",
        "audit_event",
        ["actor_type", "actor_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_event_org_created",
        "audit_event",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_event_resource",
        "audit_event",
        ["resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_event_workspace_created",
        "audit_event",
        ["workspace_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_event_workspace_created", table_name="audit_event")
    op.drop_index("ix_audit_event_resource", table_name="audit_event")
    op.drop_index("ix_audit_event_org_created", table_name="audit_event")
    op.drop_index("ix_audit_event_actor", table_name="audit_event")
    op.drop_table("audit_event")
    sa.Enum("ATTEMPT", "SUCCESS", "FAILURE", name="auditeventstatus").drop(
        op.get_bind()
    )
    sa.Enum("USER", name="auditeventactor").drop(op.get_bind())
    # ### end Alembic commands ###
