"""Add workflow error handler

Revision ID: f2e840c9fb2c
Revises: 8be6393b2ee0
Create Date: 2024-12-31 15:39:57.045107

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2e840c9fb2c"
down_revision: str | None = "8be6393b2ee0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow",
        sa.Column("error_handler", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow", "error_handler")
    # ### end Alembic commands ###
