"""Encrypt oauth tokens in workspace integrations

Revision ID: fa502336c577
Revises: ffc7da8d97b8
Create Date: 2025-06-18 00:31:34.781433

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa502336c577"
down_revision: str | None = "ffc7da8d97b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace_integration",
        sa.Column("encrypted_access_token", sa.LargeBinary(), nullable=False),
    )
    op.add_column(
        "workspace_integration",
        sa.Column("encrypted_refresh_token", sa.LargeBinary(), nullable=True),
    )
    op.drop_column("workspace_integration", "access_token")
    op.drop_column("workspace_integration", "refresh_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace_integration",
        sa.Column("refresh_token", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "workspace_integration",
        sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("workspace_integration", "encrypted_refresh_token")
    op.drop_column("workspace_integration", "encrypted_access_token")
    # ### end Alembic commands ###
