"""Add doc_url and author to BoundRegistryAction

Revision ID: fc35519b23ac
Revises: 8be6393b2ee0
Create Date: 2025-01-06 16:22:55.740238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc35519b23ac'
down_revision: Union[str, None] = '8be6393b2ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registryaction', sa.Column('doc_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('registryaction', sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registryaction', 'author')
    op.drop_column('registryaction', 'doc_url')
    # ### end Alembic commands ###
