"""Add CaseEntityLink table for case-entity associations

Revision ID: fe3ee527275e
Revises: 556803275bf5
Create Date: 2025-08-14 15:09:02.857596

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fe3ee527275e'
down_revision: str | None = '556803275bf5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_entity_link',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('surrogate_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('entity_metadata_id', sa.UUID(), nullable=True),
    sa.Column('entity_data_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_data_id'], ['entity_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_metadata_id'], ['entity_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('surrogate_id'),
    sa.UniqueConstraint('case_id', 'entity_data_id', name='uq_case_entity_link')
    )
    op.create_index('idx_case_entity_case', 'case_entity_link', ['case_id'], unique=False)
    op.create_index('idx_case_entity_metadata', 'case_entity_link', ['entity_metadata_id'], unique=False)
    op.create_index(op.f('ix_case_entity_link_id'), 'case_entity_link', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_entity_link_id'), table_name='case_entity_link')
    op.drop_index('idx_case_entity_metadata', table_name='case_entity_link')
    op.drop_index('idx_case_entity_case', table_name='case_entity_link')
    op.drop_table('case_entity_link')
    # ### end Alembic commands ###
