"""history context for approvals

Revision ID: fe8a8a928b43
Revises: 70144f614d3d
Create Date: 2025-11-07 21:32:08.873806

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe8a8a928b43"
down_revision: str | None = "70144f614d3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "approval",
        sa.Column(
            "history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "approval",
        sa.Column("recommendation_verdict", sa.String(length=16), nullable=True),
    )
    op.add_column(
        "approval",
        sa.Column(
            "recommendation_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "approval",
        sa.Column(
            "recommendation_source", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("approval", "recommendation_source")
    op.drop_column("approval", "recommendation_reason")
    op.drop_column("approval", "recommendation_verdict")
    op.drop_column("approval", "history")
    # ### end Alembic commands ###
