title: Enrich IOCs and provide triage advice for security incidents
description: |
  This playbook takes a text input or a JSON format with all the context of a security incident/alert (Investigation).
  It extracts all the IOCs (IPs, hash, domains et urls) and enriches them.
  - IPs: Passive-dns (VT), Open port (Censys et Shodan), services and ports history (Censys), Geoloc, Provider, Reputation (VT)
  - URLs: urlscan.io verdict, screenshot of the webpage
  - Hash: Reputation (VT), signature (VT), malware familly (Tria.ge et Any.run)
  It then provides triage advice for investigations (what to check/do, taking into account all the context and tools of the customer).
  It also provides a risk assessment via LLM (% of chance of being False Positive AND % of chance of being a True Legitimate).
  Finally, it provides a Remediations Plan.

entrypoint: enrich_iocs
triggers:
  - type: webhook
    ref: alert_webhook
    entrypoint: enrich_iocs

actions:
  - ref: extract_iocs
    action: core.extract_iocs
    args:
      # JSON with all the context of a security incident/alert
      input: ${{ TRIGGER.alert }}

  - ref: extract_iocs
    action: core.transform.forward
    args:
      ip_addresses: ${{ TRIGGER.alert.ip_addresses }}
      urls: ${{ TRIGGER.alert.urls }}
      hashes: ${{ TRIGGER.alert.hashes }}

  - ref: enrich_ip_addresses
    action: integrations.enrich.virustotal.analyze_ip
    for_each: ${{ for var.ip_address in ACTIONS.extract_iocs.result.ip_addresses }}
    depends_on:
      - extract_iocs
    args:
      ip_address: ${{ var.ip_address }}

  - ref: enrich_urls
    action: integrations.enrich.virustotal.analyze_url
    for_each: ${{ for var.url in ACTIONS.extract_iocs.result.urls }}
    depends_on:
      - extract_iocs
    args:
      url: ${{ var.url }}

  - ref: enrich_hashes
    action: integrations.enrich.virustotal.analyzem_malware_sample
    for_each: ${{ for var.hash in ACTIONS.extract_iocs.result.hashes }}
    depends_on:
      - extract_iocs
    args:
      file_hash: ${{ var.hash }}

  - ref: combine_iocs
    action: core.transform.forward
    depends_on:
      - enrich_ips
      - enrich_urls
      - enrich_hashes
    args:
      enriched_ip_addresses: ${{ ACTIONS.enrich_ip_addresses.result }}
      enriched_urls: ${{ ACTIONS.enrich_urls.result }}
      enriched_hashes: ${{ ACTIONS.enrich_hashes.result }}

  - ref: provide_triage_advice
    action: core.ai_action
    depends_on:
      - combine_iocs
    args:
      prompt: |
        You are an expert in security incidents. You have all the context of the incident and the enriched IOCs.
        - What would you do to investigate this incident?
        - What tools would you use?
        - What would you check?

        IoCs extracted from the alert
        -----------------------------
        IP Addresses: ${{ ACTION.combine_iocs.result.enriched_ip_addresses }}
        URLs: ${{ ACTION.combine_iocs.result.enriched_urls }}
        Hashes: ${{ ACTION.combine_iocs.result.enriched_hashes }}

  - ref: provide_risk_assessment
    action: core.ai_action
    depends_on:
      - combine_iocs
      - provide_triage_advice
    args:
      prompt: |
        You are an expert in security incidents. You have all the context of the incident and the enriched IOCs.
        - What is the risk of this incident being a False Positive?
        - What is the risk of this incident being a True Legitimate?

        IoCs extracted from the alert
        -----------------------------
        IP Addresses: ${{ ACTION.combine_iocs.result.enriched_ip_addresses }}
        URLs: ${{ ACTION.combine_iocs.result.enriched_urls }}
        Hashes: ${{ ACTION.combine_iocs.result.enriched_hashes }}

  - ref: estimate_percentage_risk
    action: core.ai_action
    depends_on:
      - combine_iocs
      - provide_triage_advice
    args:
      prompt: |
        You are an expert in security incidents. You have all the context of the incident and the enriched IOCs.

        IoCs extracted from the alert
        -----------------------------
        IP Addresses: ${{ ACTION.combine_iocs.result.enriched_ip_addresses }}
        URLs: ${{ ACTION.combine_iocs.result.enriched_urls }}
        Hashes: ${{ ACTION.combine_iocs.result.enriched_hashes }}

        Task
        ----
        - Score this alert between 0-100 for the risk of this incident being a False Positive.
        - Score this alert between 0-100 for the risk of this incident being a True Legitimate.

        Give your response as a JSON:
        ```json
        {
          "false_positive": <score>,
          "true_legitimate": <score>
        }
        ```

  - ref: provide_remediations_plan
    action: core.ai_action
    depends_on:
      - combine_iocs
      - provide_triage_advice
      - provide_risk_assessment
    args:
      prompt: |
        You are an expert in security incidents. You have all the context of the incident and the enriched IOCs.
        - What would be your remediations plan?
        - What would you do to prevent this incident from happening again?

        IoCs extracted from the alert
        -----------------------------
        IP Addresses: ${{ ACTION.combine_iocs.result.enriched_ip_addresses }}
        URLs: ${{ ACTION.combine_iocs.result.enriched_urls }}
        Hashes: ${{ ACTION.combine_iocs.result.enriched_hashes }}
