type: action
definition:
  title: Create opaque secret
  description: Create an opaque secret in a Kubernetes cluster.
  display_group: Kubernetes
  doc_url: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#create
  namespace: tools.kubernetes
  name: create_secret
  expects:
    name:
      type: str
      description: Name of the secret.
    namespace:
      type: str
      description: Namespace to create the secret in.
    data:
      type: dict[str, str]
      description: User-defined secret data.
    dry_run:
      type: bool
      description: Whether to dry run the create client-side.
      default: false
  steps:
    - ref: secret_manifest
      action: core.transform.reshape
      args:
        value:
          apiVersion: v1
          kind: Secret
          metadata:
            name: ${{ inputs.name }}
          type: Opaque
          data: ${{ inputs.data }}
    - ref: create_secret
      action: tools.kubernetes.run_command
      args:
        command:
          - "create"
          - "-f"
          - "-"
        namespace: ${{ inputs.namespace }}
        dry_run: ${{ inputs.dry_run }}
        stdin: ${{ FN.serialize_json(steps.secret_manifest.result) }}
  returns: ${{ steps.create_secret.result }}
