type: action
definition:
  title: Get pod logs
  description: Get logs from a Kubernetes pod.
  display_group: Kubernetes
  doc_url: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#logs
  namespace: tools.kubernetes
  name: get_logs
  expects:
    pod:
      type: str
      description: Pod to get logs from.
    namespace:
      type: str
      description: Namespace of the pod.
    container:
      type: str | None
      description: Container to get logs from.
      default: null
    tail_lines:
      type: int
      description: Number of lines to return from the end of the logs.
      default: 10
  steps:
    - ref: get_logs
      action: tools.kubernetes.run_command
      args:
        command:
          - "logs"
          - ${{ inputs.pod }}
        namespace: ${{ inputs.namespace }}
        args:
          - "--tail"
          - ${{ inputs.tail_lines }}
          - "-c"
          - ${{ inputs.container || "" }}
  returns: ${{ steps.get_logs.result }}
