type: action
definition:
  title: List PVC
  description: List all persistent volume claims (PVC) in a namespace.
  display_group: Kubernetes
  doc_url: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get
  namespace: tools.kubernetes
  name: list_pvc
  expects:
    namespace:
      type: str
      description: Namespace to list PVC from.
  steps:
    - ref: list_pvc
      action: tools.kubernetes.run_command
      args:
        command:
          - "get"
          - "pvc"
        namespace: ${{ inputs.namespace }}
  returns: ${{ steps.list_pvc.result }}
