type: action
definition:
  title: List secrets
  description: List all secrets in a namespace.
  display_group: Kubernetes
  doc_url: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get
  namespace: tools.kubernetes
  name: list_secrets
  expects:
    namespace:
      type: str
      description: Namespace to list secrets from.
  steps:
    - ref: list_secrets
      action: tools.kubernetes.run_command
      args:
        command:
          - "get"
          - "secrets"
        namespace: ${{ inputs.namespace }}
  returns: ${{ steps.list_secrets.result }}
