resources:
- configmap.yaml
- ui
- server
images:
- name: server
  newName: ghcr.io/tracecathq/tracecat
  newTag: 0.10.1
- name: ui
  newTag: 0.10.1
  newName: ghcr.io/tracecathq/tracecat-ui
- name: kubectl
  newTag: 1.30.0
  newName: bitnami/kubectl
- name: python
  newTag: 3.12-slim-bookworm
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: tracecat
    app.kubernetes.io/part-of: tracecat
