definition:
  title: Execute Caldera operations
  description: |
    Example playbook that executes pre-configured Caldera operations in a sequence.
    Built by Jason Ostrom (@securitypuck) for his SANS SEC598 course on security automation.
  config:
    environment: default
  entrypoint:
    expects: {}
    ref: generate_uuid
  inputs:
    caldera_api_url: <paste-your-caldera-url-here>/api/v2
  returns: null
  triggers: []
  actions:
  - action: core.transform.reshape
    args:
      value: ${{ FN.slice(FN.uuid4(), 0, 6) }}
    depends_on: []
    description: ''
    for_each: null
    ref: generate_uuid
    retry_policy:
      max_attempts: 1
      timeout: 300
    run_if: null
    start_delay: 0.0
  # Receive operations from Caldera
  - action: core.http_request
    args:
      headers:
        KEY: ${{ SECRETS.caldera.API_KEY }}
      method: GET
      url: ${{ INPUTS.caldera_api_url }}/operations
      verify_ssl: false
    depends_on:
    - generate_uuid
    description: ''
    for_each: null
    ref: receive_operations
    retry_policy:
      max_attempts: 1
      timeout: 300
    run_if: null
    start_delay: 0.0
  # Execute the Discovery operation
  - action: core.http_request
    args:
      headers:
        KEY: ${{ SECRETS.caldera.API_KEY }}
      method: POST
      payload:
        adversary:
          adversary_id: 0f4c3c67-845e-49a0-927e-90ed33c044e0
          atomic_ordering:
          - c0da588f-79f0-4263-8998-7496b1a40596
          - c1cd6388-3ced-48c7-a511-0434c6ba8f48
          - feaced8f-f43f-452a-9500-a5219488abb8
          - b6f545ef-f802-4537-b59d-2cb19831c8ed
          - 3b5db901-2cb8-4df7-8043-c4628a6a5d5a
          - 530e47c6-8592-42bf-91df-c59ffbd8541b
          - 26c8b8b5-7b5b-4de1-a128-7d37fb14f517
          - 2dece965-37a0-4f70-a391-0f30e3331aba
          - 5c4dd985-89e3-4590-9b57-71fed66ff4e2
          - 8c06ebf8-bacf-486b-bd77-21ba8c5a5777
          - ce485320-41a4-42e8-a510-f5a8fe96a644
          - b007fc38-9eb7-4320-92b3-9a3ad3e6ec25
          description: A discovery adversary
          name: Discovery
          objective: 495a9828-cab1-44dd-a0ca-66e58177d8cc
          plugin: stockpile
          tags: []
        auto_close: false
        autonomous: 1
        group: ''
        id: ${{ FN.uuid4() }}
        jitter: 2/8
        name: Operation Discovery - ${{ ACTIONS.generate_uuid.result }}
        obfuscator: plain-text
        objective:
          description: string
          goals:
          - count: 0
            operator: string
            target: string
            value: string
          id: string
          name: string
        planner:
          allow_repeatable_abilities: true
          description: string
          id: aaa7c857-37a0-4c4a-85f7-4e9f7f30e31a
          ignore_enforcement_modules:
          - string
          module: app.planners.atomic
          name: atomic
          params: {}
          plugin: null
          stopping_conditions: []
        source:
          adjustments:
          - ability_id: string
            offset: 0
            trait: string
            value: string
          facts:
          - collected_by:
            - string
            limit_count: 0
            links:
            - string
            origin_type: string
            relationships:
            - string
            score: 0
            source: string
            technique_id: string
            trait: string
            value: string
          id: ed32b9c3-9593-4c33-b0db-e2007315096b
          name: basic
          plugin: null
          relationships:
          - edge: string
            origin: string
            score: 0
            source:
              collected_by:
              - string
              limit_count: 0
              links:
              - string
              origin_type: string
              relationships:
              - string
              score: 0
              source: string
              technique_id: string
              trait: string
              value: string
            target:
              collected_by:
              - string
              limit_count: 0
              links:
              - string
              origin_type: string
              relationships:
              - string
              score: 0
              source: string
              technique_id: string
              trait: string
              value: string
          rules:
          - action: DENY
            match: .*
            trait: file.sensitive.extension
          - action: ALLOW
            match: png
            trait: file.sensitive.extension
          - action: ALLOW
            match: yml
            trait: file.sensitive.extension
          - action: ALLOW
            match: wav
            trait: file.sensitive.extension
        state: running
        use_learning_parsers: true
        visibility: 51
      url: ${{ INPUTS.caldera_api_url }}/operations
      verify_ssl: false
    depends_on:
    - receive_operations
    description: ''
    for_each: null
    ref: operation_discovery
    retry_policy:
      max_attempts: 1
      timeout: 300
    run_if: null
    start_delay: 10.0
  # Execute the Thief operation
  - action: core.http_request
    args:
      headers:
        KEY: ${{ SECRETS.caldera.API_KEY }}
      method: POST
      payload:
        adversary:
          adversary_id: 1a98b8e6-18ce-4617-8cc5-e65a1a9d490e
          atomic_ordering:
          - 6469befa-748a-4b9c-a96d-f191fde47d89
          - 90c2efaa-8205-480d-8bb6-61d90dbaf81b
          - 4e97e699-93d7-4040-b5a3-2e906a58199e
          - 300157e5-f4ad-4569-b533-9d1fa0e74d74
          - ea713bc4-63f0-491c-9a6f-0b01d560b87e
          description: An adversary to steal sensitive files
          name: Thief
          objective: 495a9828-cab1-44dd-a0ca-66e58177d8cc
          plugin: stockpile
          tags: []
        auto_close: false
        autonomous: 1
        group: ''
        id: ${{ FN.uuid4() }}
        jitter: 2/8
        name: Operation Thief - ${{ ACTIONS.generate_uuid.result }}
        obfuscator: plain-text
        objective:
          description: string
          goals:
          - count: 0
            operator: string
            target: string
            value: string
          id: string
          name: string
        planner:
          allow_repeatable_abilities: true
          description: string
          id: aaa7c857-37a0-4c4a-85f7-4e9f7f30e31a
          ignore_enforcement_modules:
          - string
          module: app.planners.atomic
          name: atomic
          params: {}
          plugin: null
          stopping_conditions: []
        source:
          adjustments:
          - ability_id: string
            offset: 0
            trait: string
            value: string
          facts:
          - collected_by:
            - string
            limit_count: 0
            links:
            - string
            origin_type: string
            relationships:
            - string
            score: 0
            source: string
            technique_id: string
            trait: string
            value: string
          id: ed32b9c3-9593-4c33-b0db-e2007315096b
          name: basic
          plugin: null
          relationships:
          - edge: string
            origin: string
            score: 0
            source:
              collected_by:
              - string
              limit_count: 0
              links:
              - string
              origin_type: string
              relationships:
              - string
              score: 0
              source: string
              technique_id: string
              trait: string
              value: string
            target:
              collected_by:
              - string
              limit_count: 0
              links:
              - string
              origin_type: string
              relationships:
              - string
              score: 0
              source: string
              technique_id: string
              trait: string
              value: string
          rules:
          - action: DENY
            match: .*
            trait: file.sensitive.extension
          - action: ALLOW
            match: png
            trait: file.sensitive.extension
          - action: ALLOW
            match: yml
            trait: file.sensitive.extension
          - action: ALLOW
            match: wav
            trait: file.sensitive.extension
        state: running
        use_learning_parsers: true
        visibility: 51
      url: ${{ INPUTS.caldera_api_url }}/operations
      verify_ssl: false
    depends_on:
    - operation_discovery
    description: ''
    for_each: null
    ref: operation_thief
    retry_policy:
      max_attempts: 1
      timeout: 300
    run_if: null
    start_delay: 10.0
  # Execute the Alice 2.0 operation
  - action: core.http_request
    args:
      headers:
        KEY: ${{ SECRETS.caldera.API_KEY }}
      method: POST
      payload:
        adversary:
          adversary_id: 50855e29-3b4e-4562-aa55-b3d7f93c26b8
          atomic_ordering:
          - 13379ae1-d20e-4162-91f8-320d78a35e7f
          - 7049e3ec-b822-4fdf-a4ac-18190f9b66d1
          - 14a21534-350f-4d83-9dd7-3c56b93a0c17
          - 6d90e6fa-9324-4eb5-93be-9f737245bd7z
          - 2afae782-6d0a-4fbd-a6b6-d1ce90090eac
          - 921055f4-5970-4707-909e-62f594234d91
          - aa6ec4dd-db09-4925-b9b9-43adeb154686
          - 65048ec1-f7ca-49d3-9410-10813e472b30
          - ece5dde3-d370-4c20-b213-a1f424aa8d03
          description: Adversary used for demoing restricted lateral movement
          name: Alice 2.0
          objective: 495a9828-cab1-44dd-a0ca-66e58177d8cc
          plugin: stockpile
          tags: []
        auto_close: false
        autonomous: 1
        group: ''
        id: ${{ FN.uuid4() }}
        jitter: 2/8
        name: Operation Alice 2.0 - ${{ ACTIONS.generate_uuid.result }}
        obfuscator: plain-text
        objective:
          description: string
          goals:
          - count: 0
            operator: string
            target: string
            value: string
          id: string
          name: string
        planner:
          allow_repeatable_abilities: true
          description: string
          id: aaa7c857-37a0-4c4a-85f7-4e9f7f30e31a
          ignore_enforcement_modules:
          - string
          module: app.planners.atomic
          name: atomic
          params: {}
          plugin: null
          stopping_conditions: []
        source:
          adjustments:
          - ability_id: string
            offset: 0
            trait: string
            value: string
          facts:
          - collected_by:
            - string
            limit_count: 0
            links:
            - string
            origin_type: string
            relationships:
            - string
            score: 0
            source: string
            technique_id: string
            trait: string
            value: string
          id: ed32b9c3-9593-4c33-b0db-e2007315096b
          name: basic
          plugin: null
          relationships:
          - edge: string
            origin: string
            score: 0
            source:
              collected_by:
              - string
              limit_count: 0
              links:
              - string
              origin_type: string
              relationships:
              - string
              score: 0
              source: string
              technique_id: string
              trait: string
              value: string
            target:
              collected_by:
              - string
              limit_count: 0
              links:
              - string
              origin_type: string
              relationships:
              - string
              score: 0
              source: string
              technique_id: string
              trait: string
              value: string
          rules:
          - action: DENY
            match: .*
            trait: file.sensitive.extension
          - action: ALLOW
            match: png
            trait: file.sensitive.extension
          - action: ALLOW
            match: yml
            trait: file.sensitive.extension
          - action: ALLOW
            match: wav
            trait: file.sensitive.extension
        state: running
        use_learning_parsers: true
        visibility: 51
      url: ${{ INPUTS.caldera_api_url }}/operations
      verify_ssl: false
    depends_on:
    - operation_thief
    description: ''
    for_each: null
    ref: operation_alice_2_0
    retry_policy:
      max_attempts: 1
      timeout: 300
    run_if: null
    start_delay: 10.0
