definition:
  title: List, normalize, and redirect SentinelOne alerts
  description: |
    Pulls SentinelOne alerts, normalizes alerts into ECS format
    and triggers a child workflow for each alert.
  entrypoint:
    ref: list_sentinelone_alerts
    expects:
      interval_minutes: int
      child_workflow_id: str
  triggers:
    - type: webhook
      ref: sentinelone_alerts_webhook
      entrypoint: list_sentinelone_alerts
  inputs:
    limit: 10
    batch_size: 10

  actions:
    - ref: list_sentinelone_alerts
      action: integrations.sentinelone.list_sentinelone_alerts
      args:
        start_time: ${{ ENV.workflow.start_time }}
        end_time: ${{ ENV.workflow.start_time + FN.minutes(TRIGGER.interval_minutes) }}
        limit: ${{ INPUTS.limit }}

    - ref: normalize_sentinelone_alerts
      action: etl.normalization.normalize_events_to_ecs
      depends_on:
        - list_sentinelone_alerts
      run_if: ${{ FN.not_empty(ACTIONS.list_sentinelone_alerts.result) }}
      args:
        pipeline: https://github.com/elastic/integrations/raw/main/packages/sentinel_one/data_stream/alert/elasticsearch/ingest_pipeline/default.yml
        data: ${{ ACTIONS.list_sentinelone_alerts.result }}

    - ref: trigger_child_workflow
      action: system.trigger_child_workflow
      depends_on:
        - normalize_sentinelone_alerts
      run_if: ${{ FN.not_empty(ACTIONS.normalize_sentinelone_alerts.result) }}
      args:
        child_workflow_id: ${{ INPUTS.child_workflow_id }}
        data: ${{ ACTIONS.normalize_sentinelone_alerts.result }}
        batch_size: ${{ INPUTS.batch_size }}
        interval_minutes: ${{ TRIGGER.interval_minutes }}
        trigger_inputs:
          alert: ${{ var.alert }}
          severity: ${{ var.detection.sentinel_one.alert.rule.severity }}
