from typing import Literal

ActionType = Literal[
    # Core primitives
    "webhook",
    "http_request",
    "data_transform",
    "condition.compare",
    "condition.regex",
    "condition.membership",
    "llm.extract",
    "llm.label",
    "llm.translate",
    "llm.choice",
    "llm.summarize",
    "send_email",
    "receive_email",
    "open_case",
    # Integrations
    "integrations.aws_cloudtrail.query_cloudtrail_logs",
    "integrations.datadog.list_detection_rules",
    "integrations.datadog.list_security_signals",
    "integrations.datadog.update_security_signal_state",
    "integrations.emailrep.check_email_reputation",
    "integrations.sublime.explode_binary",
    "integrations.sublime.hunt_messages",
    "integrations.sublime.classify_messages",
    "integrations.sublime.dismiss_messages",
    "integrations.sublime.quarantine_messages",
    "integrations.sublime.trash_messages",
    "integrations.sublime.create_message",
    "integrations.sublime.analyze_message",
    "integrations.sublime.score_message",
    "integrations.sublime.restore_message",
    "integrations.sublime.trash_message",
    "integrations.sublime.list_user_reports",
    "integrations.urlscan.analyze_url",
    "integrations.virustotal.get_domain_report",
    "integrations.virustotal.get_file_report",
    "integrations.virustotal.get_ip_address_report",
    "integrations.virustotal.get_url_report",
]
