from __future__ import annotations

import ast
from pathlib import Path


def _clean_docstring(text: str | None) -> str:
    if not text:
        return "No description provided."
    lines: list[str] = []
    for raw in text.splitlines():
        line = raw.rstrip()
        stripped = line.strip()
        if stripped in {"Args:", "Returns:", "Raises:"}:
            break
        lines.append(line)

    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    if not lines:
        return "No description provided."

    normalized: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if normalized and normalized[-1]:
                normalized.append("")
            continue

        if stripped.startswith("- "):
            normalized.append(stripped)
            continue

        if (
            normalized
            and normalized[-1]
            and (line.startswith((" ", "\t")) or not normalized[-1].startswith("- "))
        ):
            normalized[-1] = f"{normalized[-1]} {stripped}"
        else:
            normalized.append(stripped)

    expanded: list[str] = []
    for line in normalized:
        if not line:
            expanded.append("")
            continue
        if " - " not in line:
            expanded.append(line)
            continue
        lead, *tail = line.split(" - ")
        if not tail:
            expanded.append(line)
            continue
        if lead.strip():
            expanded.append(lead.strip())
        expanded.extend(f"- {chunk.strip()}" for chunk in tail if chunk.strip())

    while expanded and not expanded[-1]:
        expanded.pop()
    return "\n".join(expanded) if expanded else "No description provided."


def _is_mcp_tool(node: ast.AsyncFunctionDef) -> bool:
    for decorator in node.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        func = decorator.func
        if not isinstance(func, ast.Attribute) or func.attr != "tool":
            continue
        value = func.value
        if isinstance(value, ast.Name) and value.id == "mcp":
            return True
    return False


def main() -> None:
    root_dir = Path(__file__).resolve().parent.parent
    server_file = root_dir / "tracecat" / "mcp" / "server.py"
    output_file = root_dir / "docs" / "snippets" / "mcp-tools.mdx"

    source = server_file.read_text(encoding="utf-8")
    module = ast.parse(source)

    tools: list[tuple[str, str]] = []
    for node in module.body:
        if not isinstance(node, ast.AsyncFunctionDef):
            continue
        if not _is_mcp_tool(node):
            continue
        tools.append((node.name, _clean_docstring(ast.get_docstring(node))))

    lines = [
        "{/* Auto-generated by scripts/generate_mcp_docs.py; do not edit by hand. */}",
        "",
    ]
    for tool_name, docstring in tools:
        lines.append(f'<ResponseField name="{tool_name}" type="tool">')
        for doc_line in docstring.splitlines():
            if doc_line:
                rendered_line = (
                    f"-> {doc_line[2:]}" if doc_line.startswith("- ") else doc_line
                )
                lines.append(f"  {rendered_line}")
            else:
                lines.append("")
        lines.append("</ResponseField>")
        lines.append("")

    output_file.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
