type: action
definition:
  title: Get task
  description: Retrieve the current status of a Sublime task.
  display_group: Sublime
  doc_url: https://docs.sublime.security/reference/gettask-1
  namespace: tools.sublime
  name: get_task
  secrets:
    - name: sublime
      keys: ["SUBLIME_API_KEY"]
  expects:
    id:
      type: str
      description: Sublime task ID.
    base_url:
      type: str | None
      description: Base URL of the Sublime API.
      default: null
  steps:
    - ref: request
      action: core.http_request
      args:
        url: ${{ inputs.base_url || VARS.sublime.base_url }}/v0/tasks/${{ FN.url_encode(inputs.id) }}
        method: GET
        headers:
          Authorization: Bearer ${{ SECRETS.sublime.SUBLIME_API_KEY }}
  returns: ${{ steps.request.result.data }}
