type: action
definition:
  title: Find annotation tags
  description: Find all event tags created in Grafana annotations, optionally filtered by tag name and limited by count.
  display_group: Grafana
  doc_url: https://grafana.com/docs/grafana/latest/developers/http_api/annotations/#find-annotations-tags
  namespace: tools.grafana
  name: find_annotation_tags
  expects:
    tag:
      type: str | None
      description: Optional string to filter tags (e.g., "out" to find tags containing "out").
      default: null
    limit:
      type: int | None
      description: Maximum number of results to return (default is 100).
      default: null
    base_url:
      type: str
      description: Grafana server URL (e.g., http://localhost:3000).
      default: "http://localhost:3000"
  steps:
    - ref: grafana_find_annotation_tags
      action: core.http_request
      args:
        url: ${{ inputs.base_url }}/api/annotations/tags
        method: GET
        params:
          tag: ${{ inputs.tag }}
          limit: ${{ inputs.limit }}
    - ref: human_readable
      action: core.transform.reshape
      args:
        value:
          status: "success"
          message: "Retrieved Grafana annotation tags"
          tags_found: ${{ steps.grafana_find_annotation_tags.result.data.result.tags }}
  returns: ${{ steps.human_readable.result }}
