definition:
  actions:
  - action: tools.urlscan.lookup_url
    args:
      url: ${{ TRIGGER.url }}
    depends_on: []
    description: ''
    for_each: null
    interaction: null
    join_strategy: all
    ref: lookup_url
    retry_policy:
      max_attempts: 1
      retry_until: null
      timeout: 300
    run_if: null
    start_delay: 0.0
    wait_until: null
  - action: core.transform.reshape
    args:
      value:
        asn: ${{ ACTIONS.lookup_url.result.data.meta.processors.asn }}
        download: ${{ ACTIONS.lookup_url.result.data.meta.processors.download }}
        geoip: ${{ ACTIONS.lookup_url.result.data.meta.processors.geoip }}
    depends_on:
    - lookup_url
    description: ''
    for_each: null
    interaction: null
    join_strategy: all
    ref: extract_important_fields
    retry_policy:
      max_attempts: 1
      retry_until: null
      timeout: 300
    run_if: null
    start_delay: 0.0
    wait_until: null
  - action: core.table.insert_row
    args:
      row_data:
        asn: ${{ ACTIONS.extract_important_fields.result.asn }}
        download: ${{ ACTIONS.extract_important_fields.result.download }}
        geoip: ${{ ACTIONS.extract_important_fields.result.geoip }}
        url: ${{ TRIGGER.url }}
      table: url_blocklist
    depends_on:
    - extract_important_fields
    description: ''
    for_each: null
    interaction: null
    join_strategy: all
    ref: insert_record
    retry_policy:
      max_attempts: 1
      retry_until: null
      timeout: 300
    run_if: null
    start_delay: 0.0
    wait_until: null
  config:
    environment: default
    timeout: 300.0
  description: ''
  entrypoint:
    expects: {}
    ref: null
  error_handler: ''
  inputs: {}
  returns: ${{ ACTIONS.extract_data.result }}
  title: Enrich URL
  triggers: []
