definition:
  title: Enrich URL with VirusTotal
  description: Search for a URL in VirusTotal and list all community comments if malicious.
  config:
    environment: default
  entrypoint:
    expects: {}
    ref: search_url
  inputs: {}
  returns: null
  triggers: []
  actions:
  - action: integrations.virustotal.search_url
    ref: search_url
    args:
      url: ${{ TRIGGER.url }}
  - action: core.transform.reshape
    ref: extract_report
    args:
      value:
        stats: ${{ ACTIONS.search_url.result.data.data.attributes.last_analysis_stats }}
        url: ${{ ACTIONS.search_url.result.data.data.attributes.url }}
    depends_on:
    - search_url
  - action: integrations.virustotal.list_comments
    ref: list_comments
    run_if: ${{ ACTIONS.extract_report.result.stats.malicious > 10 }}
    args:
      url: ${{ ACTIONS.extract_report.result.url }}
    depends_on:
    - extract_report
