name: Test pnpm build

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/test-pnpm-build.yml"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/test-pnpm-build.yml"

permissions:
  contents: read

jobs:
  push-ui-to-ghcr-test:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.23.0

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/tracecathq/tracecat-ui
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000
          NEXT_PUBLIC_APP_ENV: production
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          NEXT_SERVER_API_URL: http://localhost:8000
          NODE_ENV: production
        with:
          context: frontend
          file: frontend/Dockerfile.prod
          build-args: |
            NEXT_PUBLIC_API_URL=${{ env.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_APP_ENV=${{ env.NEXT_PUBLIC_APP_ENV }}
            NEXT_PUBLIC_APP_URL=${{ env.NEXT_PUBLIC_APP_URL }}
            NEXT_SERVER_API_URL=${{ env.NEXT_SERVER_API_URL }}
            NODE_ENV=${{ env.NODE_ENV }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
